## Detector probabilidad de pago / Condicion de Deudor y Clasificacion 

In [66]:
import numpy as np

In [67]:
import pandas as pd
import seaborn  as sns
from  sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix



In [68]:
data = pd.read_csv('Default.csv', sep='\t')
data.head()

default student      balance        income
0      No      No   729.526495  44361.625074
1      No     Yes   817.180407  12106.134700
2      No      No  1073.549164  31767.138947
3      No      No   529.250605  35704.493935
4      No      No   785.655883  38463.495879

In [69]:
data.default.value_counts()

No     9667
Yes     333
Name: default, dtype: int64

## - Limpieza y balanceo de Datos

In [70]:
student_dumy= pd.get_dummies(data.student,drop_first=True,prefix="student")
student_dumy.head(3)

student_Yes
0            0
1            1
2            0

In [71]:
data = pd.concat([data,student_dumy],axis=1)

In [72]:
data.head(3)

default student      balance        income  student_Yes
0      No      No   729.526495  44361.625074            0
1      No     Yes   817.180407  12106.134700            1
2      No      No  1073.549164  31767.138947            0

In [73]:
X=data[['student_Yes','balance','income']]
y=data.default

In [74]:
X_train, X_test, y_train, y_test =train_test_split(X,y,stratify=y,random_state=12)

In [75]:
data.default.value_counts()['Yes']/data.shape[0]

0.0333

In [76]:
y_train.value_counts()['Yes']/y_train.shape[0]

0.03333333333333333

In [77]:
y_test.value_counts()['Yes']/y_test.shape[0]

0.0332

In [78]:
logistic_regression = LogisticRegression(penalty=None)
logistic_regression.fit(X_train,y_train);

### Use Markdown to Scheme the 

-Nesting_Week_1 = 20% 
-Nesting_Week_2 = 20%
-Production_Week_1 = 30%
-Production_Week_2 = 30%

-----------------------------

$$ W = \frac {\sum^n_{i=1} {w_i}X_i}{\sum^n_{i=1}w_i} 

W = weighted Average

n = number of terms to be averaged

$ w_i $ = weights applied to x Values

$X_i$ data values to be averaged

In [79]:
y_test_pred = logistic_regression.predict(X_test)
y_test_pred

array(['No', 'No', 'No', ..., 'No', 'No', 'No'], dtype=object)

In [80]:
y_test_pred_proba=logistic_regression.predict_proba(X_test)
y_test_pred_proba

array([[9.97675832e-01, 2.32416770e-03],
       [9.98876259e-01, 1.12374110e-03],
       [9.96638594e-01, 3.36140624e-03],
       ...,
       [9.67782530e-01, 3.22174700e-02],
       [9.14285262e-01, 8.57147383e-02],
       [9.99920761e-01, 7.92386434e-05]])

In [81]:
accuracy_score(y_test,y_test_pred)

0.9684

In [82]:
confusion_matrix(y_test,y_test_pred)

array([[2404,   13],
       [  66,   17]], dtype=int64)

In [83]:
logistic_regression.intercept_

array([-3.01195506])

In [84]:
logistic_regression.coef_

array([[-4.01670288e+00,  4.10753666e-03, -1.31786584e-04]])